### ISSUE TITLE
Certificate Error 

### ISSUE THREAD

**Issue by akshayinube** [gradio-app/gradio#10065]
### Describe the bug

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app./
2024/11/28 11:02:22 [W] [service.go:132] login to server failed: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-11-28T11:02:22Z is after 2024-11-28T06:24:31Z

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

def create_gradio_interface():
    def process_files_with_feedback(prescription_file_path, bills_file_path):
        yield "Processing... Please wait."
        result = process_files(prescription_file_path, bills_file_path)
        yield result

    iface = gr.Interface(
        fn=process_files_with_feedback,
        inputs=[
            gr.File(label="Document 1", type="filepath"),
            gr.File(label="Document 2", type="filepath")
        ],
        outputs=gr.HTML(label="Results"),
        title="V1.3.4",
        description="Upload Document",
    )
    return iface

if __name__ == "__main__":
    iface = create_gradio_interface()
    iface.launch(share=True)

### System Info

```shell
5.7.0
```

### Severity

Blocking usage of gradio

**Comment by tae-su-kim** [comment]
Same issue here. Workaround is to downgrade gradio to 4.44.1.

**Comment by akshayinube** [comment]
Downgrading gradio is working thank you @tae-su-kim

**Comment by hasanshahid5678** [comment]
Downgrading is not working anymore

**Comment by luvwinnie** [comment]
same here.

**Comment by abidlabs** [comment]
Should be fixed now, sorry about that folks!

**Comment by hasanshahid5678** [comment]
> Should be fixed now, sorry about that folks!

still not working for me
![Screenshot from 2024-11-28 19-00-05](https://github.com/user-attachments/assets/5fc51cbf-98d3-400e-afa0-97b2f0f96d64)

**Comment by abidlabs** [comment]
Hmm have you tried hard refreshing the page?

**Comment by hasanshahid5678** [comment]
> Hmm have you tried hard refreshing the page?

Yes, I am using colab

**Comment by hasanshahid5678** [comment]
> Hmm have you tried hard refreshing the page?

Sorry it was error from my side, didnt saw it first due to degug=False.
