### ISSUE TITLE
login to server failed: tls: failed to verify certificate: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by hasanshahid5678** [gradio-app/gradio#10066]
### Describe the bug

Since yesterday, I have been facing the issue of gradio not launching properly. It keeps printing this error and displays unexpected ui.
`Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

`Colab notebook detected. To show errors in colab notebook, set debug=True in launch()`

`
![Screenshot from 2024-11-28 17-48-48](https://github.com/user-attachments/assets/e4ac885b-d7f8-42b3-b69b-3967cc0e5bc9)
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app/.
2024/11/28 12:45:01 [W] [service.go:132] login to server failed: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-11-28T12:45:01Z is after 2024-11-28T06:24:31Z
Running on [https://localhost:7860/](https://obk54oqrggb-496ff2e9c6d22116-7860-colab.googleusercontent.com/)`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks() as demo:
    gr.Markdown("# Hello World")
demo.launch()
```

### Screenshot

![Screenshot from 2024-11-28 17-48-48](https://github.com/user-attachments/assets/6cfaa92c-56b0-49ff-80cd-c5401d83d352)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.7.0
gradio_client version: 1.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 3.7.1
audioop-lts is not installed.
fastapi: 0.115.5
ffmpy: 0.4.0
gradio-client==1.5.0 is not installed.
httpx: 0.27.2
huggingface-hub: 0.26.2
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 1.26.4
orjson: 3.10.11
packaging: 24.2
pandas: 2.2.2
pillow: 11.0.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart==0.0.12 is not installed.
pyyaml: 6.0.2
ruff: 0.8.0
safehttpx: 0.1.1
semantic-version: 2.10.0
starlette: 0.41.3
tomlkit==0.12.0 is not installed.
typer: 0.13.0
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.32.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.10.0
httpx: 0.27.2
huggingface-hub: 0.26.2
packaging: 24.2
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Should be fixed now, sorry about that folks!

**Comment by hasanshahid5678** [comment]
Still not working for me. It gives error when I submit a query
