### ISSUE TITLE
ModuleNotFoundError: No module named 'websockets.asyncio' when importing supabase

### ISSUE THREAD

**Issue by loganpearce17** [gradio-app/gradio#10661]
### Describe the bug

I am using supabase as the backend for my project and hosting it on Hugging Face. It was working about a month ago, but now I'm getting this runtime error when I try to import supabase: "ModuleNotFoundError: No module named 'websockets.asyncio'". 

I have added asyncio and websockets to my requirements.txt file. I tried to add websockets.asycio to the requirements file as well, but that caused a build error. I also did a full factory rebuild, and that didn't help either. 

Note that everything works when I run the code locally; the problem is only when I run it on Hugging Face. 

Thanks in advance!

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import supabase
```

### Logs

```shell
===== Application Startup at 2025-02-23 19:10:40 =====

Traceback (most recent call last):
  File "/home/user/app/workshops.py", line 11, in <module>
    import supabase
  File "/usr/local/lib/python3.10/site-packages/supabase/__init__.py", line 13, in <module>
    from realtime import AuthorizationError, NotConnectedError
  File "/usr/local/lib/python3.10/site-packages/realtime/__init__.py", line 9, in <module>
    from ._async.client import AsyncRealtimeClient
  File "/usr/local/lib/python3.10/site-packages/realtime/_async/client.py", line 13, in <module>
    from websockets.asyncio.client import ClientConnection, connect
ModuleNotFoundError: No module named 'websockets.asyncio'
Traceback (most recent call last):
  File "/home/user/app/workshops.py", line 11, in <module>
    import supabase
  File "/usr/local/lib/python3.10/site-packages/supabase/__init__.py", line 13, in <module>
    from realtime import AuthorizationError, NotConnectedError
  File "/usr/local/lib/python3.10/site-packages/realtime/__init__.py", line 9, in <module>
    from ._async.client import AsyncRealtimeClient
  File "/usr/local/lib/python3.10/site-packages/realtime/_async/client.py", line 13, in <module>
    from websockets.asyncio.client import ClientConnection, connect
ModuleNotFoundError: No module named 'websockets.asyncio'
```

### System Info

```shell
As mentioned earlier, the issue is only when I run the code on Hugging Face, which is presumably running the latest version of Gradio.
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Can you link to the Space for reproduction?

**Comment by freddyaboulton** [comment]
Probably fixed by #10664

**Comment by loganpearce17** [comment]
I just did a factory rebuild, and the issue is still there. Here's the repo: https://huggingface.co/spaces/Juggling/Schedule_Buddy_Updated

**Comment by loganpearce17** [comment]
That worked! Sorry for the late response; work was crazy last week. Thanks so much!!
