### ISSUE TITLE
Tackle iframe resizer issues

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#10826]
### Describe the bug

As reported by @jsulz, the presence of the certain components, such as the `gr.Dataframe` can make a Gradio app hosted on Spaces have infinitely long vertical scrolling. We've seen similar issues related to the iframe resizer on other Gradio apps, we should fix this. 

@pngwn do you want to take this on?

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/huggingface/sizzle/commit/5d4c24bdecc1364c5c4e21af4b6a6cab381264f7 (private Space)

### Logs

```shell

```

### System Info

```shell
gradio==5.20.1
```

### Severity

I can work around it

**Comment by pngwn** [comment]
Sure thing.

**Comment by aliabid94** [comment]
This space can't scroll on mobile as well: https://huggingface.co/spaces/fffiloni/Artist

**Comment by eggie5** [comment]
experiencing the same issue here for weeks https://huggingface.co/spaces/adyen/DABstep

**Comment by abidlabs** [comment]
Are you still seeing this issue in your Space @eggie5 even after updating to 5.38? I do see extra space at the bottom of the Space but not sure if it's the same issue:

<img width="1383" height="718" alt="Image" src="https://github.com/user-attachments/assets/d33f9b9b-cd38-4998-876f-4db7b423c91a" />

If you are seeing the issue, can you share a screenshot and share what browser / os you are using? cc @pngwn

**Comment by pngwn** [comment]
@eggie5's issue has been resolved by updating gradio (we have slack colab).

**Comment by pngwn** [comment]
That said, I don't think issue is fully resolved.

**Comment by abidlabs** [comment]
I still see a spacing issue at the bottom, especially after switching tabs:

https://github.com/user-attachments/assets/3a14ed54-9191-4080-9987-6a60261d7846

(Mac / Chrome)

**Comment by pngwn** [comment]
Yes me too but I wouldn't call it 'infinitely long'. The original reproduction was much worse than this.
