### ISSUE TITLE
uv run: Gradio v5.36.2 blank screen when launching app (works in v5.35.0)

### ISSUE THREAD

**Issue by kuri54** [gradio-app/gradio#11554]
### Describe the bug

When running a Gradio app with the latest Gradio version (`5.36.2`) under [uv](https://github.com/astral-sh/uv),  the application launches without any errors but the browser displays a completely blank (black) page and no UI elements are rendered. The same code loads correctly when run directly with python app.py or when using Gradio `v5.35.0` under uv.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch()
```

### Logs

```shell
Nothing is displayed in the terminal or browser console; there are no errors or stack traces.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 5.36.2
gradio_client version: 1.10.4

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 24.1.0
anyio: 4.9.0
audioop-lts is not installed.
brotli: 1.1.0
fastapi: 0.116.0
ffmpy: 0.6.0
gradio-client: 1.10.4
groovy: 0.1.2
httpx: 0.28.1
huggingface-hub: 0.33.2
jinja2: 3.1.6
markupsafe: 3.0.2
numpy: 2.3.1
orjson: 3.10.18
packaging: 25.0
pandas: 2.3.1
pillow: 11.3.0
pydantic: 2.11.7
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
ruff: 0.12.2
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.46.2
tomlkit: 0.13.3
typer: 0.16.0
typing-extensions: 4.14.1
urllib3: 2.5.0
uvicorn: 0.35.0
mcp is not installed.
pydantic: 2.11.7
authlib is not installed.
itsdangerous is not installed.


gradio_client dependencies in your environment:

fsspec: 2025.5.1
httpx: 0.28.1
huggingface-hub: 0.33.2
packaging: 25.0
typing-extensions: 4.14.1
websockets: 15.0.1
```

### Severity

I can work around it

**Comment by peilongchencc** [comment]
Yes, I'm experiencing the same issue with Gradio 5.36.2 — the interface that opens is completely blank with no UI rendered at all.

**Comment by LeonLeKan** [comment]
I had just experienced the same problem,and I found some 404 errors

<img width="811" height="362" alt="Image" src="https://github.com/user-attachments/assets/2d1e257c-54d3-44f4-a0db-aaaf70f616e1" />

Switching to lower versions such as 5.34.2 will solve the problem

**Comment by victorqin** [comment]
Having the exact same problem.

<img width="1009" height="310" alt="Image" src="https://github.com/user-attachments/assets/04ac7a81-4dba-44d2-94c2-863c9c10fc0b" />

**Comment by freddyaboulton** [comment]
Hi! I can't reproduce the error (with uv or python)

<img width="319" height="371" alt="Image" src="https://github.com/user-attachments/assets/337fc8ce-6dc4-4a0d-a32e-71b6ccd58a5b" />

<img width="1285" height="336" alt="Image" src="https://github.com/user-attachments/assets/f8c06e20-5914-4050-b196-22984ee5947d" />

Does your browser have a non-english locale? Asking because of the i18n error

**Comment by freddyaboulton** [comment]
I can reproduce if setting my location to tokyo!

<img width="1497" height="481" alt="Image" src="https://github.com/user-attachments/assets/0540b627-39e1-4d78-8c18-c46b8ea442e0" />

**Comment by rybakov-ks** [comment]
> I can reproduce if setting my location to tokyo!
> 
> <img alt="Image" width="1497" height="481" src="https://private-user-images.githubusercontent.com/41651716/465316226-0540b627-39e1-4d78-8c18-c46b8ea442e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIyNDgyOTUsIm5iZiI6MTc1MjI0Nzk5NSwicGF0aCI6Ii80MTY1MTcxNi80NjUzMTYyMjYtMDU0MGI2MjctMzllMS00ZDc4LThjMTgtYzQ2YjhlYTQ0MmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzExVDE1MzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiOWVjN2UwMDdmYzNjNzQ0NDEyZTY1YTAyMTQwODMyMjUxMmVkZTIzOGZiZWNmMjkwYjhjNjU3MjBhNGJlOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aHrXgmK2IiiVOa2dkIQG13T4LEUBWYdUXfzALxXOk5Y">

Hi! I have the same issue: when I set the browser language to English (en), the interface appears, but i18n translation doesn’t work. However, if I switch to Russian (ru), the interface stops loading:

<img width="1018" height="166" alt="Image" src="https://github.com/user-attachments/assets/812f5389-496f-413c-a2b5-3876c295f508" />

**Comment by FurkanGozukara** [comment]
yes so many people reporting this issue this need urgent fix please

**Comment by evokateur** [comment]
I'm in the unlucky browser locale club (`fr-FR`) and my Gradio Quick Start was a disaster! Not using uv, now pinned to 5.35.0

**Comment by freddyaboulton** [comment]
Hey everyone! Looks like launching gradio in SSR mode (server-side-rendering) will work regardless of the locale. Please use that if possible while we fix this (looking into this now)

<img width="965" height="487" alt="Image" src="https://github.com/user-attachments/assets/a603e76a-d602-49a6-8623-e4c63ac46eb5" />

**Comment by mikey247** [comment]
> Hey everyone! Looks like launching gradio in SSR mode (server-side-rendering) will work regardless of the locale. Please use that if possible while we fix this (looking into this now)
> 
> <img alt="Image" width="965" height="487" src="https://private-user-images.githubusercontent.com/41651716/465728905-a603e76a-d602-49a6-8623-e4c63ac46eb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI0MDU1MDEsIm5iZiI6MTc1MjQwNTIwMSwicGF0aCI6Ii80MTY1MTcxNi80NjU3Mjg5MDUtYTYwM2U3NmEtZDYwMi00OWE2LTg2MjMtZTRjNjNhYzQ2ZWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEzVDExMTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OWMzM2FiOTM2NTZlMWJmYzU5YTZiNDMxYjQ5YTQxZDdiNjIxZGY5YWVmOTM5MWI1NzkxZDBjNzU2YWM4NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LyNEbiM7TdgghDBNGWkvo8Depr0uYRa49nQZl_Le948">

I'm not sure how to do this, @freddyaboulton

**Comment by IloBe** [comment]
Having the same issue with **Gradio 5.36.2** and German-DE local settings.
Server start happens on WSL2 Ubuntu CLI, gradio app shall be shown on a Windows browser.

**Reproducible** with this **simple .py** file:
'''
import gradio as gr

def greet(name):
    return "Hello, " + name + "!"

with gr.Blocks() as demo:
    gr.Markdown("## Minimal Gradio Test")
    name = gr.Textbox(label="Name")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output)

print("Start app on localhost with debug true ...")
demo.launch(server_name="0.0.0.0", debug=True)
'''

**Workflow:**
- run script on WSL2 ubuntu terminal and starting uvicorn server
- open windows browser tab 
- start gradio app with URL http://127.0.0.1:7860
- Start console developer tool with F12 and it shows

![Image](https://github.com/user-attachments/assets/c91f764b-b59d-4ec9-a42a-7adaaba95f26)

**Comment by FurkanGozukara** [comment]
why this breaking bug still not fixed so many people complaining me :( i dont want to update all to a specific version and then change again 

i mean this issue is extremely urgent since imagine a person installs an app with gradio and see blank screen and has no idea

e.g.

<img width="1062" height="252" alt="Image" src="https://github.com/user-attachments/assets/1dc87c74-d114-4250-912b-8602722edba2" />

**Comment by kuri54** [comment]
Thank you everyone for reporting and upvoting this issue. It’s clear that many of us are affected, and I personally consider this a serious regression.

I maintain a library that relies on Gradio, and due to this bug I’ve had to pin to `v5.35.0` to keep my services running. Without knowing about this, users upgrading to the latest version may find their apps simply refuse to render, which could impact production deployments.

At this point, it would be helpful to determine whether the root cause lies in uv’s environment handling, Gradio’s webview, or some other interaction. Both uv and Gradio are fantastic tools that we depend on, so I hope the team can shed light on which component needs a fix (or a compatibility workaround). 

Thanks again for everyone’s feedback.

**Comment by FurkanGozukara** [comment]
i don't use uv and still happens with python 3.10.11 venv pip install

**Comment by myhloli** [comment]
Why not yank 5.36.2 at pypi ?

**Comment by freddyaboulton** [comment]
Hi! It has nothing to do with uv. The bug happens when you launch a gradio app without server side rendering and your browser has a non-english language locale. To avoid the bug while we look into it:

- Change you browser language to english
- Launch the app with server side rendering (set `ssr_mode=True` in `launch()`)

**Comment by androllen** [comment]
[A Downgrade to gradio==5.23 works, thanks.](https://github.com/ace-step/ACE-Step/issues/291#issuecomment-3064662262)

**Comment by pngwn** [comment]
This should be fixed in: gradio@5.37.0 which was just released. Please upgrade!

Do let us know if you notice any other issue!

**Comment by kuri54** [comment]
@pngwn 

Thank you for the quick fix! 
I’ve upgraded to `5.37.0` and can confirm that everything is working smoothly on my end so far. 
I’ll report back if I encounter any other issues.

**Comment by mikey247** [comment]
@pngwn This issue is still persistent for me. See #11560, which was closed for being a duplicate issue to this one. I have updated my fork and run the `bash scripts/install_gradio.sh` script again, but still the same error.

**Comment by pngwn** [comment]
It could be that there is an issue with the bash script. Will take a look. 

Cc @hannahblair

**Comment by gibiee** [comment]
The UI is not displayed in version **5.38.1**. (Python 3.13.5)
It renders correctly in versions 5.38.0 and 5.37.0.

```py
import gradio as gr
demo = gr.Interface(fn=lambda x: x, inputs="image", outputs="image")
demo.launch()
```

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/issues/3169

**Comment by hannahblair** [comment]
@gibee looking into it (see #11627)
