### ISSUE TITLE
Gradio 5.43.1 gpu zero error

### ISSUE THREAD

**Issue by elismasilva** [gradio-app/gradio#11765]
### Describe the bug

I am facing this bug with 5.43.1 running my app on spaces;

running locally works.

If i change SDK to 5.42.0 works on space.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

access:
https://huggingface.co/spaces/elismasilva/gradio_livelog

- go to Diffusion Pipeline Integration tab
- type a prompt 'a cat' for e.g
- click on generate.

### Logs

```shell
* Running on local URL:  http://0.0.0.0:7860, with SSR ⚡ (experimental, to disable set `ssr_mode=False` in `launch()`)
* To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 626, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 349, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 2274, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1793, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 754, in async_iteration
    return await anext(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 745, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2476, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 728, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 892, in gen_wrapper
    response = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/spaces/zero/wrappers.py", line 314, in gradio_handler
    worker.arg_queue.put(((args, kwargs), GradioPartialContext.get()))
  File "/usr/local/lib/python3.10/site-packages/spaces/zero/gradio.py", line 63, in get
    progress=LocalContext.progress.get(),
LookupError: <ContextVar name='progress' at 0x7f65417bea20>
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 5.43.1
gradio_client version: 1.12.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 24.1.0
anyio: 4.9.0
audioop-lts is not installed.
brotli: 1.1.0
fastapi: 0.116.1
ffmpy: 0.6.1
gradio-client: 1.12.1
groovy: 0.1.2
httpx: 0.28.1
huggingface-hub: 0.34.2
jinja2: 3.1.6
markupsafe: 3.0.2
numpy: 2.2.6
orjson: 3.11.1
packaging: 25.0
pandas: 2.3.1
pillow: 11.3.0
pydantic: 2.11.7
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
ruff: 0.12.5
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.47.2
tomlkit: 0.13.3
typer: 0.16.0
typing-extensions: 4.14.1
urllib3: 2.5.0
uvicorn: 0.35.0
mcp is not installed.
pydantic: 2.11.7
authlib is not installed.
itsdangerous is not installed.


gradio_client dependencies in your environment:

fsspec: 2025.7.0
httpx: 0.28.1
huggingface-hub: 0.34.2
packaging: 25.0
typing-extensions: 4.14.1
websockets: 15.0.1
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
There was an issue with ZeroGPU which should have been fixed. Can you try now @elismasilva?

**Comment by elismasilva** [comment]
> There was an issue with ZeroGPU which should have been fixed. Can you try now @elismasilva?

Have they fixed it yet? I tried now and the problem persists.

**Comment by freddyaboulton** [comment]
The `spaces` package used in ZeroGPU spaces needs to be updated. @cbensimon is on it!

**Comment by abidlabs** [comment]
Sorry it should have been fixed this morning around 10:30 am est. Could you try one more time?

**Comment by elismasilva** [comment]
I tested it and it still didn't work. I'll test it again later.

**Comment by abidlabs** [comment]
Huh interesting, I'll raise this internally

**Comment by abidlabs** [comment]
can you push an empty commit to the Space?

(on a side note, such a fantastic space and custom component!)

**Comment by elismasilva** [comment]
I'm glad you liked the component. I've made some improvements to it since version 0.0.1. I just uploaded it to 0.0.4 and it's working perfectly now. Thank you very much for your support!

<img width="1951" height="626" alt="Image" src="https://github.com/user-attachments/assets/53a646f5-0700-4ff1-bda6-f0abc7989a57" />
