### ISSUE TITLE
fill_height=True does not fill up the browser's height in Gradio 6

### ISSUE THREAD

**Issue by Jaryllan** [gradio-app/gradio#12510]
### Describe the bug

fill_height property used to work in gradio 5, but after upgraded to Gradio 6, the property no longer work. It doesn't fill up the height of the browser.

To temporary fix this, i had to add the following custom CSS.

`div.sidebar-parent > div.contain > div.column { flex-grow: 1 }`

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
import time

def print_like_dislike(x: gr.LikeData):
    print(x.index, x.value, x.liked)

def response(question, history):
    response = "**That's cool!**"
    content = ""
    for character in response:
        content += character
        time.sleep(0.05)
        yield content

with gr.Blocks(fill_height=True) as demo:
    chatbot = gr.Chatbot(elem_id="chatbot", like_user_message=True)

    chat_interface = gr.ChatInterface(fn=response, 
                     chatbot=chatbot,
                     fill_height=True, 
                     fill_width=False, 
                     multimodal=True)
    
    chat_interface.textbox.file_types = [".png", ".jpg"]

    chatbot.like(print_like_dislike, None, None)

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7864)
```

### Screenshot

<img width="1915" height="992" alt="Image" src="https://github.com/user-attachments/assets/960bef01-9883-4bda-9297-03f23239555e" />

### Logs

```shell

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 6.0.2
gradio_client version: 2.0.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 24.1.0
anyio: 4.10.0
audioop-lts is not installed.
brotli: 1.1.0
fastapi: 0.116.1
ffmpy: 0.6.1
gradio-client: 2.0.1
groovy: 0.1.2
httpx: 0.28.1
huggingface-hub: 1.0.0rc5
jinja2: 3.1.6
markupsafe: 3.0.2
numpy: 2.3.2
orjson: 3.11.3
packaging: 25.0
pandas: 2.3.2
pillow: 11.3.0
pydantic: 2.12.4
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
safehttpx: 0.1.7
semantic-version: 2.10.0
starlette: 0.47.3
tomlkit: 0.13.3
typer: 0.16.1
typing-extensions: 4.15.0
uvicorn: 0.35.0
mcp is not installed.
pydantic: 2.12.4
authlib is not installed.
itsdangerous is not installed.


gradio_client dependencies in your environment:

fsspec: 2025.7.0
httpx: 0.28.1
huggingface-hub: 1.0.0rc5
packaging: 25.0
typing-extensions: 4.15.0
```

### Severity

I can work around it

**Comment by avan06** [comment]
The content below has been modified.

It worked fine for me in Gradio 5, but after upgrading to Gradio 6, I encountered a similar issue where the `gr.Textbox` component does not automatically expand its height as the content increases. I also used a CSS workaround to temporarily fix this:

```css
/* Enable auto-growing height for textareas based on content in Gradio 6 */
.gradio-container .wrap .contain .input-container textarea { field-sizing: content; }
```

**Comment by freddyaboulton** [comment]
I think this has been fixed by #12569 

### Version 6

<img width="1971" height="727" alt="Image" src="https://github.com/user-attachments/assets/ed0530ea-60e9-40bb-aab0-df661364d7c4" />

### Version 5
<img width="1923" height="929" alt="Image" src="https://github.com/user-attachments/assets/70f74afe-1be4-466e-8a4a-94b60c61b2a7" />

**Comment by debagos** [comment]
Still an issue in 6.2.0
https://github.com/gradio-app/gradio/pull/12569 did not fix it, please re-open.

Minimal repro:
```py
import gradio as gr
import random

def random_response(message, history):
    return random.choice(["Yes", "No"])

with gr.Blocks(fill_width=True, fill_height=True) as demo:
    gr.ChatInterface(random_response, fill_width=True, fill_height=True)

demo.launch()
```

**Comment by Felix-Tr** [comment]
+1, would appreciate re-opening the issue.
My workaround is to give ChatInterface a ChatBot component with custom height in css units

```
import gradio as gr
import random

def random_response(message, history):
    return random.choice(["Yes", "No"])

chatbot = gr.Chatbot(
    label="Chatbot",
    autoscroll=True,
    elem_id="chatbot",
    height="calc(100vh - 500px)",
    like_user_message=True
)

with gr.Blocks(fill_width=True, fill_height=True) as demo:
    gr.ChatInterface(random_response, chatbot=chatbot, fill_width=True, fill_height=True)

demo.launch()
```

**Comment by debagos** [comment]
This issue still exists in 6.15.2
