### ISSUE TITLE
Auth is broken on Gradio 3.0

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`auth` doesn't seem to be working in 3.0

### Reproduction

Check `demo\hello_login`

### System Info

```shell
3.0b5
```

### Severity

blocker

**Comment by abidlabs** [comment]
Still an issue, see: https://huggingface.co/spaces/abidlabs/hello-login

**Comment by abidlabs** [comment]
We are looking into it! cc @aliabid94 

@YuliangXiu, to confirm, you are looking to add a username/password login to a Gradio demo you are hosting on Hugging Spaces? Can you simply make the Space private?

**Comment by abidlabs** [comment]
Closing thanks to #3049 by @freddyaboulton!

**Comment by AlanMars** [comment]
> Closing thanks to #3049 by @freddyaboulton!

Hi abidlabs, 

Thanks for your fixing. It seems that this issue has been resolved. 
It can work well in Google Chrome Version 113.0.5672.92 (Official Build) (arm64) on "PC". (Gradio 3.29.0 + Python 3.8.9 + Huggingface Space). 

But we have the same failed auth issue on the Mobile Chrome Web browser (Chrome, Safari). Do you have this issue on your Phone Browser? 

- Alan M

**Comment by efbsecond** [comment]
Hi all - I am still having an auth issue with Gradio hosted on HF Spaces. The login works as expected on Firefox and Chrome on MacOS but fails on MacOS Safari and iOS Safari. The failure results in an empty login box refreshing after each correct login attempt - rendering the space unusable. Happy to provide further documentation or create a demo repo.

**Comment by ARusterholz-edu** [comment]
> Hi all - I am still having an auth issue with Gradio hosted on HF Spaces. The login works as expected on Firefox and Chrome on MacOS but fails on MacOS Safari and iOS Safari. The failure results in an empty login box refreshing after each correct login attempt - rendering the space unusable. Happy to provide further documentation or create a demo repo.

I am also receiving this issue in Chrome and Safari as of April 2024. It happens regularly in Chrome Private Tabs or in Safari. 

The space is currently only consistently useable in Firefox, but I can usually use it in chrome browser while logged in and not in private tab.

**Comment by chigkim** [comment]
I can use the auth feature on MacOS Safari, but not on Ios Safari. It just redirects to login page.

**Comment by freddyaboulton** [comment]
Make sure your ios browser allows third party cookies @chigkim

**Comment by freddyaboulton** [comment]
The issue is specifically for spaces (or any website that embeds a gradio demo hosted on another site).

On Spaces, the actual server is hosted on a different domain and then served over an iframe on the space page. So that's why the authentication cookie counts as "third party". It's technically coming from a different site.

You can access the domain your space is hosted on directly and the issue shouldn't happen. You can get the domain your space is hosted on by clicking the `Embed this Space` button in the options:

![get_subdomain_of_space](https://github.com/gradio-app/gradio/assets/41651716/a82b62c0-9ba0-421d-98fe-2a15df896422)

**Comment by chigkim** [comment]
> You can access the domain your space is hosted on directly and the issue shouldn't happen. You can get the domain your space is hosted on by clicking the `Embed this Space` button in the options:

Awesome, that worked!
Then basically, if you 1) host your code on HF, 2) utilize auth feature, and 3) and don't want to tell people to turn of Prevent Cross-Site Tracking, instead of embedding on a website, you should really link the domain (hf.space) where your space is hosted on, and point users to the webpage directly.
No other option than hosting on your own domain. Am I understanding it correctly?
Thanks!
