### ISSUE TITLE
Blocks Slider change() outputs incorrect value on drag

### ISSUE THREAD

**Issue by mindwrapped** [gradio-app/gradio#1453]
### Describe the bug

If you click and drag on the slider then it will pass an incorrect value to change(). 

If you only click on the slider then it will pass the correct value to change().

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/mindwrapped/blocks-slider-test 

Click and drag -> incorrect value (old value, not the current one displayed on the slider)
Click -> correct value (same value as on the slider)

```python
import gradio as gr

def update_value(val):
  return f'Value is set to {val}'

demo = gr.Blocks()

with demo:
  inp = gr.Slider(0, 100, label='Value')
  md = gr.Markdown('Select a value')

  inp.change(fn=update_value, inputs=inp, outputs=md)

demo.launch()
```

### Screenshot

![Screen Shot 2022-06-02 at 1 11 00 PM](https://user-images.githubusercontent.com/61097415/171719313-c4325208-8482-45ec-9983-e565a3e036cf.png)

### Logs

```shell
From HF Spaces:

Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
Huggingface Spaces
Gradio: 3.0.10
```

### Severity

blocking upgrade to latest gradio version

**Comment by cyyeh** [comment]
I found this issue happened when it is deployed using Spaces, there's no issue if I run this application locally.

**Comment by aliabid94** [comment]
Will fix, thanks for raising this issue!

**Comment by NimaBoscarino** [comment]
I'm running into this as well on Gradio 3.3. Here's a notebook to reproduce: https://colab.research.google.com/drive/1JoDcK5R8lcA7Ty4-zlXnQNBwKXdfgRpb?usp=sharing

Same as mentioned above, works fine locally but on Colab + Spaces it's broken.

**Comment by abidlabs** [comment]
This should be solved by #2436, so moving to the 4.0 milestone

**Comment by abidlabs** [comment]
Special case of #1954, so closing this issue

**Comment by axkoenig** [comment]
Hi there, 
I think the issue still persists when there is some lag introduced inside the `update_value` function mentioned above. 
Consider the below example:
```python
import gradio as gr

def update_value(val):
  import time
  time.sleep(2) # simulate ML model inference
  return f'Value is set to {val}'

demo = gr.Blocks()

with demo:
  inp = gr.Slider(0, 100, label='Value')
  md = gr.Markdown('Select a value')

  inp.change(fn=update_value, inputs=inp, outputs=md)

demo.launch()
```
If you drag the slider quickly from left to right, you'll end up with the slider evaluating to 1, but its final value is 46. 

<img width="762" alt="Screen Shot 2023-06-01 at 16 35 40" src="https://github.com/gradio-app/gradio/assets/50868646/ee151cd3-513a-4520-b5d3-aded111be958">

I think this is because under the hood the .update() method is called when the slider is **starting** to be dragged, however not when it is **released**.  Is there a way to call `update` again once the slider is released? 

I'm on the latest gradio version 
```bash
pip list | grep gradio
gradio                                3.32.0
gradio_client                         0.2.5
```
