### ISSUE TITLE
Plotly legend does not appear in `Plot` component

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1632]
### Describe the bug

I ran this demo in gradio 3.0.20 and found two problems: 
1. Plots generated in Plotly mode have no legend. 
2. Pictures cannot be generated in Bokeh mode.

https://github.com/gradio-app/gradio/blob/main/demo/outbreak_forecast/run.py

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Plotly:
![ksnip_20220625-140541](https://user-images.githubusercontent.com/41098760/175760806-5f5042ea-7712-4a66-a185-f377e8087e85.png)

Bokeh:
![ksnip_20220625-140633](https://user-images.githubusercontent.com/41098760/175760813-46cb96f4-2b9a-4e1a-8fc1-4ea311772579.png)

### Logs

```shell
See image above.
```

### System Info

```shell
gradio 3.0.20
ubuntu 20.04
chrome
```

### Severity

annoying

**Comment by dawoodkhan82** [comment]
@Zengyf-CVer @freddyaboulton I can't seem to reproduce. Maybe this was fixed by another PR?
<img width="629" alt="Screen Shot 2022-08-02 at 5 59 20 PM" src="https://user-images.githubusercontent.com/12725292/182501776-70bcf8c4-38ad-4be8-95ad-73fc2d08ebf1.png">

**Comment by dawoodkhan82** [comment]
> @Zengyf-CVer @freddyaboulton I can't seem to reproduce. Maybe this was fixed by another PR? <img alt="Screen Shot 2022-08-02 at 5 59 20 PM" width="629" src="https://user-images.githubusercontent.com/12725292/182501776-70bcf8c4-38ad-4be8-95ad-73fc2d08ebf1.png">

Probably fixed by this https://github.com/gradio-app/gradio/pull/1732

**Comment by Zengyf-CVer** [comment]
@dawoodkhan82 You try to use gradio 3.1.3, the problem is still not solved. You check the version of gradio you are using.

**Comment by abidlabs** [comment]
Created a separate issue to track bokeh (#1942). Let's use this issue for the plot legend

**Comment by dawoodkhan82** [comment]
> @dawoodkhan82 You try to use gradio 3.1.3, the problem is still not solved. You check the version of gradio you are using.

Are you referring to the bokeh problem or the plotly legend problem? I don't see the plotly legend problem anymore. Unless I'm missing something.

**Comment by abidlabs** [comment]
@dawoodkhan82 I think the problem only happens when you open the demo in a new tab (as opposed to viewing it in a jupyter notebook). I just tested the `demo/outbreak_forecast/run.py` on `main` and when I open the demo in a new tab, I don't see the plotly legend:

<img width="997" alt="image" src="https://user-images.githubusercontent.com/1778297/182772119-d53da61d-25c6-4cf1-a556-0b5712c00722.png">

**Comment by dawoodkhan82** [comment]
> @dawoodkhan82 I think the problem only happens when you open the demo in a new tab (as opposed to viewing it in a jupyter notebook). I just tested the `demo/outbreak_forecast/run.py` on `main` and when I open the demo in a new tab, I don't see the plotly legend:
> 
> <img alt="image" width="997" src="https://user-images.githubusercontent.com/1778297/182772119-d53da61d-25c6-4cf1-a556-0b5712c00722.png">

Weird, seems to be the same issue causing #1692 . Ive taken a look, and can't seem to figure it out. Will spend more time on this later.

**Comment by abidlabs** [comment]
Oh yeah looks like duplicate issues. We can close this one?

**Comment by dawoodkhan82** [comment]
Closing this; because this issue is captured in #1692
