### ISSUE TITLE
Gradio interface css bug

### ISSUE THREAD

**Issue by mbjamil92** [gradio-app/gradio#1666]
### Describe the bug

I am trying to create an interface under gr.blocks to get a specific color. It gets displayed in jupyter but when i click on the actual link it shows me default theme.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

def func(id):
    id = df[df['id'] ==id]
return id

demo = gr.Blocks(css="""
                    body {
                      background-color: black !important
                    }""")
with demo:
    gr.Markdown(
        """
    # Welcome To My Interface:
    """
    )
    list=[1,2,3,4]
    input = gr.Dropdown(list)
    btn = gr.Button("Submit")
    output = [gr.outputs.Dataframe())]
    btn.click(fn=func, inputs=input, outputs=output)

demo.launch(share=True)

### Logs

```shell
n/a no errors
```

### System Info

```shell
gradio 3.0.20
chrome
i7
```

### Severity

annoying

**Comment by pngwn** [comment]
Please provide some screenshots, or link to a full reproduction. Additionally, please describe what you expect to happen with the above code and what is actually happening. It isn't clear to me what this issue is reporting.

**Comment by EliottZemour** [comment]
I think I managed to reproduce the bug mentioned by @mbjamil92 

### Reproduce

With gradio>=3.0.20 : running the following cell in jupyter

```python
import gradio as gr

def dummy_func(name):
    return "Hello " + name

name = gr.inputs.Textbox(label='Name')

out1 = gr.outputs.Textbox(label="Output")

gr.Interface(
    fn=dummy_func, 
    inputs=[name],
    outputs=out1,

    description="Issue #1666", css="""
    body {
        background: rgb(131,58,180);
        background: linear-gradient(90deg, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 50%, rgba(252,176,69,1) 100%);
    }
    """,
    article = "Demo",
    enable_queue= True).launch()
```
gives the following notebook preview:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/57868384/181035072-7acd466d-000c-496f-ad27-ba8f0dc54998.png">

However, when opening the app in the browser, the default theme is applied
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/57868384/181035485-c9e5ab74-00c8-41d3-b199-19a82a233b4c.png">

### Workaround

Gradio 3.0 works fine (both for `Interface` and `Blocks`objects) 🎉.
```
pip install gradio==3.0
```

**Comment by abidlabs** [comment]
Thanks @EliottZemour for the reproduction! @pngwn I think this might be related to: https://github.com/gradio-app/gradio/blob/ccd8e18a174c1ac261a0f52f0175ad1165eeb03a/ui/packages/app/src/main.ts#L292

**Comment by mbjamil** [comment]
@EliottZemour your help solved my problem, thank you so much.

**Comment by dawoodkhan82** [comment]
This seems to have been fixed. @abidlabs I can't reproduce. Can you confirm?

**Comment by abidlabs** [comment]
Actually, I still see it @dawoodkhan82. Here's jupyter:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/1778297/183529080-002770eb-c0b8-400d-9441-073d4e9574dc.png">

And here's in a new browser tab:

<img width="979" alt="image" src="https://user-images.githubusercontent.com/1778297/183529108-e23ba44a-c1bb-4883-9b46-f2ab09a3b34b.png">

Same behavior in both Chrome and Edge browsers

**Comment by dawoodkhan82** [comment]
@abidlabs I tested it; it's the same issue as #1632 & #1692. The same fix fixes all three issues. But it's a naive fix that probably causes regressions elsewhere; will wait for @pngwn to take a look.

<img width="936" alt="Screen Shot 2022-08-09 at 12 51 10 PM" src="https://user-images.githubusercontent.com/12725292/183710988-c48f3b9a-3f8b-45e2-bbd2-10f316be4713.png">
<img width="1326" alt="Screen Shot 2022-08-09 at 12 51 14 PM" src="https://user-images.githubusercontent.com/12725292/183710996-1ccea01d-4ec5-417a-961e-98add95c3643.png">

**Comment by dawoodkhan82** [comment]
@mbjamil @EliottZemour @abidlabs You actually have to use `.gradio-container` instead of `body`. That should fix the issue.

**Comment by abidlabs** [comment]
Nice! Can confirm that fixes it for me @dawoodkhan82!
