### ISSUE TITLE
Textbox.change() event performance issues

### ISSUE THREAD

**Issue by altryne** [gradio-app/gradio#2159]
### Describe the bug

Origin  thread here with perfomance breakdown: 
https://github.com/hlky/stable-diffusion/issues/220 

But TL;DR - adding a .change event on a text box, even without sending the params to a python function, and even with empty js function, has performance issues, unrelated to the actual Textbox or params that are passed through .

It seems that when there are a lot of images loaded in a Gallery item (some folks of ours have 50) 
.change event freezes the browser 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. checkout https://github.com/hlky/stable-diffusion-webui
2. install https://github.com/hlky/stable-diffusion-webui/commit/320ea01d113096e5d99715b3adbe6b82eb9c0059
3. run `gradio webui_playground.py` 
4. switch number to 50 and hit enter (doesn't matter what the prompt says, it doesn't generate anything, just loads 50 random images from the web
5. try to type

### Screenshot

![CleanShot 2022-09-01 at 17 25 19@2x](https://user-images.githubusercontent.com/463317/188030771-c7451737-1918-4b46-ac64-295d8de45d51.jpg)

4 is a snapshot of 50 loaded images with NO .change at all
3 is with .change and empty JS call
2 is without the scrollWidth code
and
1 is the latest.

### Logs

```shell
see screenshot
```

### System Info

```shell
Latest Gradio
```

### Severity

annoying

**Comment by JoshuaKimsey** [comment]
It doesn't even need 50, tbh. At 20-25, it begins misbehaving in a really annoying way (the aforementioned backspace thing).

Good find though! Hopefully Gradio can fix this? Or a workaround can be found.

**Comment by freddyaboulton** [comment]
I think it's related to the size of the images in the gallery.

I can reproduce if the image is 2214 x 1180 but not if it's 256 x 256.

### Fast typing 

```python
import gradio as gr

with gr.Blocks() as demo:

    text = gr.Text()
    gr.Gallery(value=["lion.jpg"] * 50)
    mirror = gr.Text()
    text.change(lambda s: s[::-1], inputs=text, outputs=mirror)

demo.launch()
```
![fast_gallery](https://user-images.githubusercontent.com/41651716/188038332-27085d04-23b3-4df2-b8c7-642df29b9cd7.gif)

### Slow gallery
```python
import gradio as gr

with gr.Blocks() as demo:

    text = gr.Text()
    gr.Gallery(value=["twitter.png"] * 50)
    mirror = gr.Text()
    text.change(lambda s: s[::-1], inputs=text, outputs=mirror)

demo.launch()
```
![slow_gallery](https://user-images.githubusercontent.com/41651716/188038347-d84791a8-5d4b-4405-a8dd-02fa13ddc0ae.gif)


### Big image
<img width="1107" alt="twitter" src="https://user-images.githubusercontent.com/41651716/188038435-3db94601-619b-478c-8353-92850a5fb624.png">


### Slow image
![lion](https://user-images.githubusercontent.com/41651716/188038443-8e22c30e-01fd-4d91-84a0-f5b6bde4cfda.jpg)

**Comment by abidlabs** [comment]
I can't reproduce this issue anymore. It may have been fixed when we moved from base64 to temporary files for the Gallery component. 

Here's the steps that I took to reproduce this:
1. Download https://user-images.githubusercontent.com/41651716/188038435-3db94601-619b-478c-8353-92850a5fb624.png as "large-image.png"
2. Run the following demo:

```py
import gradio as gr

with gr.Blocks() as demo:

    text = gr.Text()
    gr.Gallery(value=["large-image.png"] * 50)
    mirror = gr.Text()
    text.change(lambda s: s[::-1], inputs=text, outputs=mirror)

demo.launch()
```

I don't see any responsiveness issues. I'll go ahead and close unless someone is still experiencing issues in the latest version of gradio?

**Comment by abidlabs** [comment]
Closing, feel free to reopen if anyone is able to reproduce. Thanks!

**Comment by dragos240** [comment]
Tested on Gradio 3.39.0, still happening for me (unless a later update fixed it):

```py
import gradio as gr

with gr.Blocks() as demo:

    text = gr.Text()
    mirror = gr.Text()
    text.change(lambda s: s, inputs=text, outputs=mirror)

demo.launch()
```

It takes some tries sometimes, as you can see, but randomly it still doesn't always update correctly. This is happening a lot with my project which has more moving parts (which is using 3.33.1), sometimes leading to textboxes being used as input for config files not completely capturing output and saving partial data. Demo:
![Animation](https://github.com/gradio-app/gradio/assets/704081/dbf26f7a-04b0-4aea-9fe6-e6fb002ab634)

**Comment by dragos240** [comment]
I'm not sure how to re-open this issue (I think I would need permission to do so), so pinging @abidlabs
