### ISSUE TITLE
Video player behavior on iOS/Safari 

### ISSUE THREAD

**Issue by radames** [gradio-app/gradio#3134]
### Describe the bug

On iOS and Safari, if you switch between video sources the player stop working. It get stuck on a weird state

https://huggingface.co/spaces/haoheliu/audioldm-text-to-audio-generation

maybe related #2987, and older issues? #2651 #3119.

Another improvement idea for iOS, could we have [`playsinline`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-playsinline) true [here](https://github.com/gradio-app/gradio/blob/f062c7e1fd635ce6b8be704ca88ad62a0c303bec/ui/packages/video/src/Player.svelte#LL115-L132C3)? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here is a Space with multiple cached examples, if you switch between the videos on Safari or iOS you'll be able to reproduce the error

https://huggingface.co/spaces/haoheliu/audioldm-text-to-audio-generation

### Screenshot

This screenshot is on Safari, but the same error occurs on iOS
https://user-images.githubusercontent.com/102277/217081181-b3ca09bb-62e2-4d94-a27d-6586c52ba0e8.mp4

### Logs

```shell
none
```

### System Info

```shell
3.17.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
I believe that this has been fixed with https://github.com/gradio-app/gradio/pull/3117. We'll release a new version today or tomorrow to test out. (Or you can try with the version on `main`: https://gradio.app/docs/main/)

**Comment by radames** [comment]
hi @abidlabs , I can confirm that the problem persist using the main version and #3117. Considering the issue, maybe we should fallback to a much simpler player on iOS/Safari. Until the api fully compatible with Chrome/Firefox.

**Comment by abidlabs** [comment]
Hmmmm I'll defer to @pngwn
