### ISSUE TITLE
Takes an enormous amount of time to load a large video

### ISSUE THREAD

**Issue by tomchang25** [gradio-app/gradio#3845]
### Describe the bug

Takes an enormous amount of time to load a large video (Remain white screen).

Both Audio and Video components have the this issue.

File works fine.

Since assigned to `video.value` is working fine, I suspect the issue may be with postprocessing.

In addition, I am pretty sure that my previous fork did not have this issue (around 6 months ago?).

### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Phase 1: 1-minute, Video

Immediately

#### Phase 2: 5-minute, Video

20 seconds

#### Phase 3: 20-minute, Video

Approximately 5 ~ more than 30  minutes. Tested 3 times with varying times.

#### Phase 3: 70-minute, Video

Definitely more than 30 minutes.

#### Phase 4: 70-minute, Audio

Definitely more than 30 minutes.

#### Phase 5: 60-minute, Video, but downloaded from YouTube and assigned to `video.value`

2 minutes

#### Phase 6: Same as Phase 5, but performed again

2 seconds (cached?)

#### Phase 7: 60-minute, Video, File

1 minutes 30 seconds

### Screenshot

![image](https://user-images.githubusercontent.com/31534748/231842799-171cdf19-0570-4e6a-b41d-810950db42dd.png)

### Logs

```shell
Not exist
```

### System Info

```shell
v3.25.1b2
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
I wonder if its the conversion to base64. If so could be a manifestation of #3779

**Comment by tomchang25** [comment]
Thanks @freddyaboulton, I will take a look. Additionally, I believe #3842 is related to same issue .

**Comment by tomchang25** [comment]
![image](https://user-images.githubusercontent.com/31534748/231999778-2c74bfd9-f4c8-47a9-ab68-b95a26e66a7a.png)

Yeah, It's cause by base64.
I will take a look at the code and see if I can fix this.

**Comment by tomchang25** [comment]
Done. I'll clean up these debug code messes and then create a pull request.

**Comment by axjing** [comment]
I have also encountered the same problem. Have you solved it? I have looked at many issues, but still don't know how to solve it. I am in a hurry, thank you for your guidance.

**Comment by abidlabs** [comment]
Hi, we no longer use base64, so closing this issue.
