### ISSUE TITLE
Index.js issues?

### ISSUE THREAD

**Issue by Data-drone** [gradio-app/gradio#4460]
### Describe the bug

My Gradio app that worked 12 hours ago now seems to have issues when loading. No errors server side.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Versions pinned: 
```bash
pip install fastapi==0.95.2 gradio==3.20.1
``` 

app:
```python

from fastapi import FastAPI
from fastapi.responses import RedirectResponse
import gradio as gr

fastapi_app = FastAPI()
gradio_app = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")

@fastapi_app.get("/")
def redirect_to_gradio():
    return RedirectResponse(url="/gradio")

app = gr.mount_gradio_app(fastapi_app, gradio_app, path='/gradio')

```

trigger: 

```bash
uvicorn basic_app:app --host 0.0.0.0 --port 7777
```

12 hrs ish ago, everything loaded fine in browser. Now I get: 
![image](https://github.com/gradio-app/gradio/assets/4410493/750d6469-5dbf-4b38-bf28-c9f38d29abb3)

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/4410493/750d6469-5dbf-4b38-bf28-c9f38d29abb3)

### Logs

```shell
python shows no errors just browser
```

### System Info

```shell
gradio = 3.20.1
os = Ubuntu 22.04.2 LTS
browser = chrome Version 114.0.5735.110 (Official Build) (64-bit)
```

### Severity

blocking all usage of gradio

**Comment by Data-drone** [comment]
With the latest version I get this: https://github.com/gradio-app/gradio/issues/3472

**Comment by abidlabs** [comment]
Hi @Data-drone is this still an issue with the latest version of gradio? We've fixed #3472

**Comment by Data-drone** [comment]
![image](https://github.com/gradio-app/gradio/assets/4410493/1325f69c-6b3a-4b1a-bf93-782f7a2a55e0)

I am getting this with `gradio-3.47.1`

**Comment by freddyaboulton** [comment]
Really weird @Data-drone . I can't reproduce locally. Maybe something changed with `cloud.databricks.com`?

**Comment by Data-drone** [comment]
I'll see if I can find out more info. Are you able to point into what I should be looking at? I am not a web dev

**Comment by freddyaboulton** [comment]
Can you also try to pin gradio_client to 0.0.1?

**Comment by Data-drone** [comment]
I investigated some more and pinning gradio_client didn't work

**Comment by abidlabs** [comment]
Hi @Data-drone sorry I know this is an old issue, but if you are still facing this problem, can you please check if the latest version of `gradio` (4.21) still has this issue? We made some fixes to how Gradio works behind proxies which may have solved this issue

**Comment by Data-drone** [comment]
Okay will try to find the time

**Comment by abidlabs** [comment]
Thanks @Data-drone! I'm going to close this for now since I believe this issue is solved, but can reopen if needed.

**Comment by Data-drone** [comment]
Hi @abidlabs I finally managed to try and I am using this app command: 

```
import gradio as gr

CUSTOM_PATH = "/driver-proxy/o/4953176047938121/0327-132800-5tl1wbti/"

io = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox")

if __name__ == '__main__':

    io.launch(root_path=CUSTOM_PATH)
```

I have set `GRADIO_SERVER_NAME` and `GRADIO_SERVER_PORT` as well.

The app is being started with; `!python3 my_app.py`

It looks like it is still looking for `index.css` under the raw server uri rather than adding the `root_path` to that as well

**Comment by Data-drone** [comment]
I just tried with `GRADIO_ROOT_PATH` set and with the full uri ie `http://blahblahblah/CUSTOM_PATH` and that seems to work but still getting an errow with `assets` unlike before the buttons are rendering though 

![image](https://github.com/gradio-app/gradio/assets/4410493/99299cca-664b-4e03-b1a3-9121e8ebc0ec)

**Comment by freddyaboulton** [comment]
I think that error can be ignored if the page loads correctly. Note to @pngwn and @abidlabs though
