### ISSUE TITLE
Gradio cannot be started under window system

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#6910]
### Describe the bug

- gradio version 4.12.0
- window 10 system
- python 3.8.0

run python code: 

```python 
import gradio as gr
import time
def my_function(x, progress=gr.Progress()):
    progress(0, desc="Starting...")
    time.sleep(1)
    for i in progress.tqdm(range(100)):
        time.sleep(0.1)
    return x
gr.Interface(my_function, gr.Textbox(), gr.Textbox()).queue().launch()

```

![image](https://github.com/gradio-app/gradio/assets/41098760/a26bf540-4f02-4afa-8fc3-5377e73da44b)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import time
def my_function(x, progress=gr.Progress()):
    progress(0, desc="Starting...")
    time.sleep(1)
    for i in progress.tqdm(range(100)):
        time.sleep(0.1)
    return x
gr.Interface(my_function, gr.Textbox(), gr.Textbox()).queue().launch()

```

### System Info

```shell
- gradio version 4.12.0
- window 10 system
- python 3.8.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Apparently, this was a bug in Python itself: https://www.reddit.com/r/Python/comments/eobtwm/systemerror_no_locals_when_loading_str/, that should be fixed in the latest version of python 3.8

**Comment by Zengyf-CVer** [comment]
@abidlabs 
I upgraded python to the latest version, but the problem is still not solved.

![image](https://github.com/gradio-app/gradio/assets/41098760/7d802c6d-2696-4fa1-b7db-d55474091c25)

**Comment by abidlabs** [comment]
Interesting, can you try a later version of Python, such as Python 3.10?
