### ISSUE TITLE
Gradio chatbot cannot display audio in Chrome 

### ISSUE THREAD

**Issue by Southpika** [gradio-app/gradio#6917]
### Describe the bug

When I use multimodal input/output in gradio.chatbot, the audio type cannot be displayed correctly in Chrome but it is correctly displayed in Safari
![image](https://github.com/gradio-app/gradio/assets/122620817/366d8d3b-91e4-4bf6-ab07-da72522ab0a3)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import os
import time

# Chatbot demo with multimodal input (text, markdown, LaTeX, code blocks, image, audio, & video). Plus shows support for streaming text.


def print_like_dislike(x: gr.LikeData):
    print(x.index, x.value, x.liked)


def add_text(history, text):
    history = history + [(text, None)]
    return history, gr.Textbox(value="", interactive=False)


def add_file(history, file):
    history = history + [((file.name,), None)]
    return history


def bot(history):
    response = "**That's cool!**"
    history[-1][1] = ""
    for character in response:
        history[-1][1] += character
        time.sleep(0.05)
        yield history


with gr.Blocks() as demo:
    chatbot = gr.Chatbot(
        [],
        elem_id="chatbot",
        bubble_full_width=False,
        avatar_images=(None, (os.path.join(os.path.dirname(__file__), "avatar.png"))),
    )

    with gr.Row():
        txt = gr.Textbox(
            scale=4,
            show_label=False,
            placeholder="Enter text and press enter, or upload an image",
            container=False,
        )
        btn = gr.UploadButton("📁", file_types=["image", "video", "audio"])

    txt_msg = txt.submit(add_text, [chatbot, txt], [chatbot, txt], queue=False).then(
        bot, chatbot, chatbot, api_name="bot_response"
    )
    txt_msg.then(lambda: gr.Textbox(interactive=True), None, [txt], queue=False)
    file_msg = btn.upload(add_file, [chatbot, btn], [chatbot], queue=False).then(
        bot, chatbot, chatbot
    )

    chatbot.like(print_like_dislike, None, None)


demo.queue()
if __name__ == "__main__":
    demo.launch()

```

### System Info

```shell
gradio:4.9.0
system:MacOS
```

### Severity

I can work around it

**Comment by dawoodkhan82** [comment]
Thanks for filing @Southpika, will take a look!

**Comment by dawoodkhan82** [comment]
@Southpika I can't seem to reproduce your issue. What type of file are you trying to upload?

**Comment by dawoodkhan82** [comment]
Actually, @Southpika it seems like this has been fixed by this [PR](https://github.com/gradio-app/gradio/pull/6899).

**Comment by Southpika** [comment]
Okay, thanks.

**Comment by Southpika** [comment]
Can I pip install from PR#6899? I use `pip install https://gradio-builds.s3.amazonaws.com/fea5545d4e199819f8d511b39562c38a9559ce44/gradio-4.12.0-py3-none-any.whl`, but it did not fix yet.

**Comment by dawoodkhan82** [comment]
Sorry, @Southpika are ou still seeing the issue, even after installing from the whl?

**Comment by Southpika** [comment]
No, so I want to know whether it is true that downloading from that command. @dawoodkhan82

**Comment by dawoodkhan82** [comment]
The PR had been merged. So you can install gradio from main

**Comment by Southpika** [comment]
Oh, Thx, but can you please give me a command to install gradio from main~ many thanks~ @dawoodkhan82

**Comment by freddyaboulton** [comment]
Hi @Southpika ! I think this is fixed on version >= 4.13.0. I think we can close?
