### ISSUE TITLE
UI not displaying properly because path to theme.css is not using provided root_path

### ISSUE THREAD

**Issue by PaulClas** [gradio-app/gradio#7934]
I have tried all the solutions listed in this issue as well as #3798, #3662, #3482, #3472 and https://stackoverflow.com/questions/61641514/css-not-recognized-when-served-with-fastapi. 

Solutions that I have tried include:

- Mounting the subapp to my FastAPI app
- Providing a root_path to the FastAPI declaration
- Providing a root_path to the mount_gradio_app() method
- Using both the mount function from FastAPI in conjunction with the mount_gradio_app()
- Downgrading and upgrading gradio to 3.50.1, 4.19.0, 4.20.0, 4.21.0, 4.25.0

My issue is the same as stated in the issue title of #3472. When running behind a proxy and load balancer, the gradio app requests the theme.css at the root of the url and not after the url+prefix. I have tried providing the root_path at the app.mount_gradio_app(root_path=) level and at the app=FastAPI(rooth_path=) level.

The gradio app runs at the provided root_path but the theme.css file is requested at the url without the root_path:

<img width="1170" alt="Screenshot 2024-04-04 at 3 29 04 PM" src="https://github.com/gradio-app/gradio/assets/6021481/d501ea55-c1f7-4743-bf01-03fccb71f641">

I have tried a few different releases from gradio and the gradio python client and have the problem persisting.

This is a sample version of the two solutions I have tried in my code that don't provide the right url to get the theme.css. Both ways work to have the gradio app running with the prefix at https//:abc.com/app/gradio but the theme is requested at https//:abc.com/gradio and fails.

Try 1:
```from fastapi import FastAPI
import gradio as gr
import uvicorn

app = FastAPI(root_path="/app")

@app.get('/')
def hello():
    return {"message":"hello"}

g_app = gr.Interface(
    lambda x: f"Hello {x}",
    "textbox",
    "textbox",
)

app = gr.mount_gradio_app(app, g_app, path="/gradio")

uvicorn.run(app,host="0.0.0.0",port=8080)
```

Try 2:
```
from fastapi import FastAPI
import gradio as gr
import uvicorn

app = FastAPI()

@app.get('/')
def hello():
    return {"message":"hello"}

g_app = gr.Interface(
    lambda x: f"Hello {x}",
    "textbox",
    "textbox",
)

app = gr.mount_gradio_app(app, g_app, path="/gradio",root_path="/app")

uvicorn.run(app,host="0.0.0.0",port=8080)
```

Thx for the help.

_Originally posted by @PaulClas in https://github.com/gradio-app/gradio/issues/3472#issuecomment-2038081429_

**Comment by abidlabs** [comment]
Hmm I thought this was fixed. Let me look into this

**Comment by PaulClas** [comment]
Requirements I am using @abidlabs 

<img width="317" alt="Screenshot 2024-04-04 at 4 10 31 PM" src="https://github.com/gradio-app/gradio/assets/6021481/1655e4dc-1df6-4596-a2a8-ffa130a7ea72">

**Comment by abidlabs** [comment]
> the gradio app requests the theme.css at the root of the url and not after the url+prefix

Can you specify what the root of the url is here, and what the url+prefix is? If the url is sensitive, you can use a placeholder, but I need to understand what the format of the correct and incorrect urls are

**Comment by PaulClas** [comment]
> > the gradio app requests the theme.css at the root of the url and not after the url+prefix
> 
> Can you specify what the root of the url is here, and what the url+prefix is? If the url is sensitive, you can use a placeholder, but I need to understand what the format of the correct and incorrect urls are

The root url is : https://example.com/api/sql-agent

The path that I want to mount the gradio interface to is https://example.com/api/sql-agent/gradio

So the root_path (prexi) is: root_path="/api/sql-agent"

**Comment by abidlabs** [comment]
Can you please go to `https://example.com/api/sql-agent/gradio/config` and tell me what the value of the "root" key is in that json? Again you can use placeholders

**Comment by PaulClas** [comment]
"root":"https://example.com/api/sql-agent/gradio"

**Comment by abidlabs** [comment]
Ok so the root looks correct, but for some reason its not being used in the request for theme.css, hmm

**Comment by pngwn** [comment]
It looks like it being loaded from the correct location from the screenshot of the request in the original issue. It just doesn't seem to exist.

**Comment by PaulClas** [comment]
The theme loads from the url without the root_path @pngwn 

The theme is actually loading from https//:example.com/gradio/theme.css and not https//:example.com/api/sql-agent/gradio/theme.css

**Comment by pngwn** [comment]
What why is that url showing in the request pane?

**Comment by abidlabs** [comment]
Oh yeah good point @pngwn the URL from your screenshot @PaulClas is `https//:example.com/api/sql-agent/gradio/theme.css` so it does look like its loading from the right place

**Comment by abidlabs** [comment]
But according to your screenshot, as @pngwn pointed, the request is being made to `https//:example.com/api/sql-agent/gradio/theme.css`, which does include the prefix, right?

**Comment by PaulClas** [comment]
> But according to your screenshot @PaulClas, as @pngwn pointed, the request is being made to `https//:example.com/api/sql-agent/gradio/theme.css`, which does include the prefix, right?

@pngwn and @abidlabs  you are correct. I was forcing the theme.css file as a redirect. This is the screenshot with the correct link that returns a 404
<img width="1016" alt="Screenshot 2024-04-04 at 5 15 53 PM" src="https://github.com/gradio-app/gradio/assets/6021481/556e1499-70b6-4bc5-94d6-3bc31630f806">


And the root in the config is just: https://example.com/gradio

**Comment by abidlabs** [comment]
Can you clarify? -- How were you forcing the redirect? How did the root in the config change? Is this a different Gradio app?

**Comment by PaulClas** [comment]
@abidlabs as a solution attempt: I was intercepting the call and changing the path in the header for the correct one.

**Comment by pngwn** [comment]
We need to see the request url in the right sidebar. The files list always just shows the file name. 

It would be helpful if you could give the exact code you are using, the config (without components, dependencies, layout), and the request info for theme.css (and it also looks like the info route is failing too). 

Your original post had several snippets, so I'm not sure what I should be looking at.

**Comment by pngwn** [comment]
It's very hard for us to debug this without a reproduction. I've check and the theme case does use the config.root value, so I'm guessing the problem is either in the js client or the backend.

**Comment by PaulClas** [comment]
I understand @pngwn. Here are some clarifications:

This is a screenshot where you can see the full request as well as the request for the theme.css failing:
<img width="1786" alt="Screenshot 2024-04-04 at 5 25 37 PM" src="https://github.com/gradio-app/gradio/assets/6021481/45af9614-2772-463b-b2b7-8d29a257bdae">

as for the code :
```
app = FastAPI()

@app.get("/")
def read_main():
    return {"message": "The app Tac-o-Tac is ready v1.0.0"}
    
with gr.Blocks(title="Tac-o-tac v1.0.0") as demo:
# More code here for the interface

app = gr.mount_gradio_app(app, demo,path="/gradio", root_path="/api/sql-agent")

```

**Comment by abidlabs** [comment]
Agree with @pngwn this behavior is unusual and may be specific to your proxy / load_balancer set up. Basically, it seems to me that the proxy or load balancer isn't forwarding the headers as needed by Gradio to reconstruct the full URL: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx

One workaround you could try is to pass in the full url as your root path, so instead of just the prefix, do something like:

```py
app = FastAPI()

@app.get("/")
def read_main():
    return {"message": "The app Tac-o-Tac is ready v1.0.0"}
    
with gr.Blocks(title="Tac-o-tac v1.0.0") as demo:
# More code here for the interface

app = gr.mount_gradio_app(app, demo,path="/gradio", root_path="https//:example.com/api/sql-agent")

```

**Comment by PaulClas** [comment]
Why would all other files for the frontend be passed with the correct url in the header and the theme.css file as well as assets/index-a889f790.css and info use the url without the prefix ? I have found four other issues that recall the same issue with gradio (https://github.com/gradio-app/gradio/issues/3798, https://github.com/gradio-app/gradio/issues/3662, https://github.com/gradio-app/gradio/pull/3482, https://github.com/gradio-app/gradio/issues/3472)

**Comment by PaulClas** [comment]
@abidlabs Trying with the full url as root_path fails. The endpoint is not found.

**Comment by abidlabs** [comment]
And what is config.root in this case?

**Comment by PaulClas** [comment]
The config file is not accessible. I just get a 404 not found at the endpoint when using root_path="url"

**Comment by abidlabs** [comment]
@PaulClas can you try installing from this PR and see if solves the issue? Installation instructions will show up shortly on the PR: https://github.com/gradio-app/gradio/pull/7938

**Comment by PaulClas** [comment]
Will do @abidlabs Thank you each of you @pngwn for your help.

**Comment by PaulClas** [comment]
Will do @abidlabs 

What is the difference between providing app=FastAPI(root_path) and then mounting with FastAPI versus using app.mount_gradio_app(root_path) ?

**Comment by abidlabs** [comment]
Will go ahead and close this for now since we can't repro. Happy to reopen if we get a step-by-step repro.

**Comment by PaulClas** [comment]
> @PaulClas there's no difference, the root path provided in `app.mount_gradio_app(root_path)` gets set as the FastAPI root path:
> 
> https://github.com/gradio-app/gradio/blob/6a4bf7abe29059dbdc6a342e0366fdaa2e4120ee/gradio/routes.py#L187
> 
> Just FYI #7938 has been merged into `main` and we'll include in the upcoming release. But we'll probably need to close this issue in the absence of a repro

I added the pip install command to my dockerfile for deployment but it didn't solve the issue. I havec looked into our nginx settings and I still can't pinpoint why the root-path is not passed to theme.css and other files.

@abidlabs is there a way you know off to pass the theme.css as a static file that can be linked to the frontend when loaded by the DOM ?

**Comment by abidlabs** [comment]
That's very strange, can't think of what the issue might be --

> @abidlabs is there a way you know off to pass the theme.css as a static file that can be linked to the frontend when loaded by the DOM ?

We don't support that with a public api,you'd need to edit the gradio source files to do this.

**Comment by PaulClas** [comment]
It's a shame. I have at least 4 gradio interfaces we wanted to deploy using cloud run. This issue means I'll need to migrate to another ML app service.

**Comment by abidlabs** [comment]
If you can provide a step-by-step [repro](https://stackoverflow.com/help/minimal-reproducible-example) that will allow reproduce the issue you're describing, we're still happy to take a look and can reopen the issue

**Comment by jrowen** [comment]
I'm seeing the same missing `theme.css` behavior with v4.25.0.  Rolling back to v4.20.0 seems to provide a temporary fix.

**Comment by abidlabs** [comment]
@jrowen can you provide more details on your Gradio app and how it is deployed?

**Comment by PaulClas** [comment]
@abidlabs I have deployed my front-end app as a separate cloud run using demo.launch(server_name,server_port,root_path) with the same reverse proxy, load_balancer and nging settings as before. The theme.css is passed properly when using this way. This really seems like an issue specifically related to the mount_gradio_app() method and the root_path=XXX having bugs.

**Comment by jrowen** [comment]
One more quick update, I'm still seeing a 404 for one css file, but this doesn't seem to impact the usability of my app.

![image](https://github.com/gradio-app/gradio/assets/1530030/2fad8c8b-56cb-4f80-81d4-18e3fb5a8e7a)

**Comment by abidlabs** [comment]
Nope as we don't have a repro. @luvwinnie if you can provide a minimal code example that we can use to reproduce the issue above, we can reopen this issue. See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by duynguyen-0203** [comment]
I had the same problem with version 4.26.0, and going back to version 4.20.0 helped me solve the problem. But I hope this problem can be completely resolved in the next versions.

**Comment by roma-glushko** [comment]
https://github.com/gradio-app/gradio/issues/3472#issuecomment-2208973201 @abidlabs here is a fully running example that showcases the problem.

**Comment by Wenyu0010** [comment]
> I had the same problem with version 4.26.0, and going back to version 4.20.0 helped me solve the problem. But I hope this problem can be completely resolved in the next versions.

you solution helped me ~ thanks bro~

**Comment by peterb154** [comment]
Im having the same issue. Using gradio mounted to /gradio. App is in AWS behind Cloudfront. `/theme.css` and `assets/index-CKyT5UbA.css` are being routed to the root of the application, rather than on the mounted path of `gradio`. 

Here is my temporary fix, as the `theme.css` 404 seems to be the thing that makes the website un-usable - I created a route for `/theme.css` before the `/` route and redirected it to the gradio path. 

```python
...
app = gr.mount_gradio_app(app, demo, path="/gradio", auth_dependency=get_user)

@app.get("/theme.css")
def theme(request: Request):
    # Bug in gradio when mounted to a subpath behind a proxy 
    # https://github.com/gradio-app/gradio/issues/7934
    logger.warning(f"Redirecting to /gradio/{request.url.path}")
    return RedirectResponse(url=f"/gradio{request.url.path}?{request.query_params}")


@app.get("/")
def public(request: Request, user: dict = Depends(get_user)):
    ...
```

**Comment by aminrabinia** [comment]
I'm still having issue with this: 

GET http://0.0.0.0:8080/assets/index-CKyT5UbA.css net::ERR_ABORTED 404 (Not Found)
