### ISSUE TITLE
theme.css doesn't map to correct port.

### ISSUE THREAD

**Issue by kingsznhone** [gradio-app/gradio#8129]
### Describe the bug

When using 4.27.0, Set app runs on a selected port. App can't load correctly.
Check with F12, theme.css is point to defaut port.
<img width="527" alt="f3928f7267fb5874973f39d248836da" src="https://github.com/gradio-app/gradio/assets/35349300/5d5f3b61-bc01-4a5f-b09d-8b562224d2dd">

Downgrade to 3.50.2, theme.css is map to correct port.
![image](https://github.com/gradio-app/gradio/assets/35349300/3da5b30a-83b4-4d0b-b51c-c24a78eb3ba0)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
demo.launch(server_port=8443)
```

### System Info

```shell
ubuntu 22.04 LTS
python 3.10
gradio latest
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
Ooooh

**Comment by abidlabs** [comment]
Interesting, what's the URL in which your Gradio app is running? 

Can you describe more how your Gradio app is deployed? Is it behind an nginx proxy?

**Comment by kingsznhone** [comment]
> Interesting, what's the URL in which your Gradio app is running? 
> 
> Can you describe more how your Gradio app is deployed? Is it behind an nginx proxy?

it is running on a gpu rential platform, local port is 6006，reverse proxy by platform to outside 8443
I guess it's something like nginx .

**Comment by bf96163** [comment]
I also find the path /login redirected to wrong address i run my gradio in port 7001  i want to proxy it to 8001/img2txt here is my nginx.conf （the server listen to 80 is to fix the problem theme.css redirect to 80 problem）  `events {  
    # events block configuration  
}  
http{
    server {
    listen 8001;
    server_name _; 
    location /assets/ {
        rewrite ^/assets/(.*)$ /img2txt/assets/$1 break;
        proxy_pass http://127.0.0.1:7001/img2txt/;

    }
    location /img2txt/ {
        proxy_pass http://127.0.0.1:7001/img2txt/;
#        rewrite ^/img2txt/(.*) /$1 break;
        proxy_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
#        auth_basic "password please";
#       auth_basic_user_file /etc/nginx/password;
    }

    # 其他配置...
    }
    server {
    listen 80;
    server_name _;
    location /img2txt/{
    proxy_pass http://127.0.0.1:7001/img2txt/;
    }
    }
}`  after added server listen to 80 the theme.css loaded correctly ，but after i click login button（yes i use password of gradio） i got another error this is the url i submit  ：”http://192.168.8.122/img2txt/login“ but it should call ”http://192.168.8.122:8000/img2txt/login“  mybe they are the same bug（like theme.css load error in nginx）

**Comment by 1390806607** [comment]
@bf96163 Hello, have you solved it yet

**Comment by bars0um** [comment]
Have the same issue...in developer tools console I see attempts to load theme.css from localhost instead of localhost:8181 which is where the app is serving from

**Comment by abidlabs** [comment]
Hi @bars0um I'm looking into this issue, can you please describe how your app is deployed as well? Is it behind a proxy?

**Comment by bf96163** [comment]
> @bf96163 Hello, have you solved it yet

no

**Comment by bf96163** [comment]
> Can you all please try changing:
> 
> ```
>         proxy_set_header Host $host;
> ```
> 
> to
> 
> ```
>         proxy_set_header Host $http_host;
> ```
> 
> in your nginx configuration?


OK i tried i change all my work to the "/" path not the img2txt path ,and the problem still there :
In mycase ，the theme.css goes to wrong url as before (should goes to http://192.168.8.122:8001/theme.css but it goes to http://192.168.8.122/theme.css) and heart beat goes to the wrong url as before （should go to http://192.168.8.122:8001/heartbeat/vyum226pkk but it goes to http://192.168.8.122/heartbeat/vyum226pkk） and 
http://192.168.8.122:8001/assets/index-CZPZ-bmc.css this file status is " 404 Not Found" (as before)

these configs are used this time: 
``` events {
    # events block configuration  
}
http{
    server {
    listen 8001;
    server_name _;}
    location /assets/ {
        rewrite ^/assets/(.*)$ /img2txt/assets/$1 break;
        proxy_pass http://127.0.0.1:7001/;
    }
    location /img2txt/ {
        proxy_pass http://127.0.0.1:7001/;
#        rewrite ^/img2txt/(.*) /$1 break;
        proxy_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    }
} ```

**Comment by bf96163** [comment]
> Can you all please try changing:
> 
> ```
>         proxy_set_header Host $host;
> ```
> 
> to
> 
> ```
>         proxy_set_header Host $http_host;
> ```
> 
> in your nginx configuration?

I suspect that some hard-coding or incorrectly configured items in the svelte framework caused the auto-generated link points to port 80

**Comment by abidlabs** [comment]
I believe that this issue may have been fixed now. Can y'all please try installing `gradio` from `main` like this:

```
pip install https://gradio-builds.s3.amazonaws.com/94a1143686733c7fe16e204764b9a3e7240ccf02/gradio-4.31.5-py3-none-any.whl
```

and check to see if the app is working?

**Comment by abidlabs** [comment]
Going to close for now, but we can reopen if this is still not fixed.

**Comment by bars0um** [comment]
I've tried the version you've shared, tried going to 4.39.0, dropping to 4.20.0... but I still see the app loading theme.css from the :80 port...is anyone else having luck with this fix?

**Comment by yiliu-mt** [comment]
Same problem here

**Comment by andrejridzik** [comment]
I am having this exact problem with version 4.42.0... Unfortunately, I can't use the workaround with port 80 :( .
@abidlabs Any idea how to solve this? I am not able to use gradio in my case then..
