### ISSUE TITLE
MissingSchema Error

### ISSUE THREAD

**Issue by vanztj18** [gradio-app/gradio#83]
Hello, whenever I try to run a Gradio interface I get this error. I am running these in a Google Colab Notebook, this happens on the ML examples on the website, and in my personal project. These worked fine before a few days ago, but now they've stopped working without me making any changes to my code.

Thank you!
`---------------------------------------------------------------------------
MissingSchema                             Traceback (most recent call last)
<ipython-input-6-30e9b31b4482> in <module>()
      3 fare = gr.inputs.Slider(minimum=0, maximum=1000, default=100, label="Fare (british pounds)")
      4 
----> 5 gr.Interface(predict_survival, [sex, age, fare], "label", live=True).launch();

7 frames
/usr/local/lib/python3.6/dist-packages/requests/models.py in prepare_url(self, url, params)
    386             error = error.format(to_native_string(url, 'utf8'))
    387 
--> 388             raise MissingSchema(error)
    389 
    390         if not host:

MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?`

**Comment by aliabid94** [comment]
should be fixed now!

**Comment by raisanjivj6693** [comment]
Still getting the same error

Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by ingasilk-virtusize** [comment]
I'm also having this issue when running `iface.launch(share=True)` in jupyter lab notebook. It works fine locally. When I do `requests.get("https://api.gradio.app")` I get 200 response.
gradio Version: 2.7.5.2
jupyter lab version 3.1.1
python version 3.8.10
Any suggestions on how to make it work?

**Comment by abidlabs** [comment]
Has this ever worked for you before? I.e. is this a new issue or is this first time you are trying Gradio in this environment?

**Comment by ingasilk-virtusize** [comment]
It's the first time I'm trying Gradio in this environment. I only started using Gradio a couple days ago.

**Comment by abidlabs** [comment]
Ok and can you check that your code is working with Gradio in a different environment, like a colab notebook? https://colab.research.google.com/

I'm trying to understand whether its a function of the code or the environment

**Comment by ingasilk-virtusize** [comment]
Yes, it's working in a Colab notebook with the same version of Gradio.

**Comment by abidlabs** [comment]
Ok in that case, it must be an issue with the environment. Which OS are you using? And to confirm, are you running jupyter lab locally or remotely?

**Comment by ingasilk-virtusize** [comment]
I'm using OS Catalina 10.15.6. And yes, I'm running the notebook locally. I could upgrade to Monterey and see if that solves the issue.

**Comment by ingasilk-virtusize** [comment]
Getting the same error with MacOS Monterey 12.2.1

**Comment by abidlabs** [comment]
Can you try upgrading to `gradio==2.8.0` and tell me what you see?

**Comment by ingasilk-virtusize** [comment]
I upgraded to 2.8.2 and it works! Thank you so much!!

**Comment by abidlabs** [comment]
Glad to hear the issue is resolved!

**Comment by AJaveiro** [comment]
MissingSchema                             Traceback (most recent call last)
[<ipython-input-62-048bc8c6ae59>](https://localhost:8080/#) in <cell line: 35>()
     33   outputs=output
     34   )
---> 35 demo.launch(share=True)

7 frames
[/usr/local/lib/python3.10/dist-packages/requests/models.py](https://localhost:8080/#) in prepare_url(self, url, params)
    437 
    438         if not scheme:
--> 439             raise MissingSchema(
    440                 f"Invalid URL {url!r}: No scheme supplied. "
    441                 f"Perhaps you meant [https://{url}?](https://{url}/?)"

MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://none/?



Getting this error in google collab, even after upgradation of gradio

**Comment by ChanduDevelops** [comment]
i have same error even in the colab notebook.

**Comment by freddyaboulton** [comment]
The share api was down for a bit but it's back up now. We're looking at the root cause.
