### ISSUE TITLE
Custom Component : cc gradio build Error

### ISSUE THREAD

**Issue by Josephrp** [gradio-app/gradio#9445]
### Issue : `gradio cc build` returns and error in windows

it's impossible to build my custom component !

### Ref :

https://github.com/MedTonic/Gradio-Seq-Diff

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```sh
git clone https://github.com/MedTonic/Gradio-Seq-Diff
cd gradio-seq-diff
gradio cc build
```

### Screenshot

```sh
ValueError: Could not find `@gradio/preview`. Run `npm i -D @gradio/preview` in your frontend folder.
```

running the command doesnt remove the error

### Logs

```shell
MeMyself@DESKTOP-BA808PC MINGW64 ~/seq_diff (main)
$ gradio cc build
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 📦 Building package in seq_diff                                                                                      │
│ 🔢 Package will use version 0.0.2 defined in pyproject.toml file. Set --bump-version to automatically bump the       │
│ version number.                                                                                                      │
│ ✅ Documentation generated in demo\space.py and README.md. Pass --no-generate-docs to disable auto documentation.    │
│                                                                                                                      │
│ 🟠 The docs were generated in simple mode. Updating python to a version greater than 3.9 will result in richer       │
│ documentation.                                                                                                       │
│ 🎨 Building frontend                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Python312\Lib\site-packages\gradio\cli\commands\components\build.py:140 in _build                                 │
│                                                                                                                      │
│   137 │   │   │   )                                                                                                  │
│   138 │   │   │                                                                                                      │
│   139 │   │   │   if gradio_node_path.returncode != 0:                                                               │
│ ❱ 140 │   │   │   │   raise ValueError(                                                                              │
│   141 │   │   │   │   │   "Could not find `@gradio/preview`. Run `npm i -D @gradio/preview` in                       │
│   142 │   │   │   │   )                                                                                              │
│   143                                                                                                                │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │           _demo_dir = WindowsPath('C:/Users/MeMyself/seq_diff/demo')                                             │ │
│ │          _demo_name = 'app.py'                                                                                   │ │
│ │          _demo_path = WindowsPath('C:/Users/MeMyself/seq_diff/demo/app.py')                                      │ │
│ │        _readme_path = WindowsPath('C:/Users/MeMyself/seq_diff/README.md')                                        │ │
│ │      build_frontend = True                                                                                       │ │
│ │        bump_version = False                                                                                      │ │
│ │ component_directory = WindowsPath('C:/Users/MeMyself/seq_diff')                                                  │ │
│ │       generate_docs = True                                                                                       │ │
│ │    gradio_node_path = CompletedProcess(args=['C:\\Program Files\\nodejs\\node.EXE', '-e',                        │ │
│ │                       "console.log(require.resolve('@gradio/preview'))"], returncode=1, stdout=b'',              │ │
│ │                       stderr=b'node:internal/modules/cjs/loader:641\r\n      throw e;\r\n      ^\r\n\r\nError    │ │
│ │                       [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in                              │ │
│ │                       C:\\Users\\MeMyself\\seq_diff\\frontend\\node_modules\\@gradio\\preview\\package.json\r\n  │ │
│ │                       at exportsNotFound (node:internal/modules/esm/resolve:304:10)\r\n    at                    │ │
│ │                       packageExportsResolve (node:internal/modules/esm/resolve:594:13)\r\n    at resolveExports  │ │
│ │                       (node:internal/modules/cjs/loader:634:36)\r\n    at Module._findPath                       │ │
│ │                       (node:internal/modules/cjs/loader:724:31)\r\n    at Module._resolveFilename                │ │
│ │                       (node:internal/modules/cjs/loader:1211:27)\r\n    at Function.resolve                      │ │
│ │                       (node:internal/modules/helpers:190:19)\r\n    at [eval]:1:21\r\n    at                     │ │
│ │                       runScriptInThisContext (node:internal/vm:209:10)\r\n    at                                 │ │
│ │                       node:internal/process/execution:118:14\r\n    at [eval]-wrapper:6:24 {\r\n  code:          │ │
│ │                       \'ERR_PACKAGE_PATH_NOT_EXPORTED\'\r\n}\r\n\r\nNode.js v20.17.0\r\n')                       │ │
│ │                live = <gradio.cli.commands.display.LivePanelDisplay object at 0x000001E455D4DC70>                │ │
│ │                name = WindowsPath('C:/Users/MeMyself/seq_diff')                                                  │ │
│ │                node = 'C:\\Program Files\\nodejs\\node.EXE'                                                      │ │
│ │        package_name = 'gradio_seq_diff'                                                                          │ │
│ │                path = WindowsPath('.')                                                                           │ │
│ │      pyproject_toml = {'build-system': {'requires': ['hatchling', 'hatch-requirements-txt',                      │ │
│ │                       'hatch-fancy-pypi-readme>=22.5.0'], 'build-backend': 'hatchling.build'}, 'project':        │ │
│ │                       {'name': 'gradio_seq_diff', 'version': '0.0.2', 'description': 'Visualize Sequences and    │ │
│ │                       their Diffs Using MSAplot', 'readme': 'README.md', 'license': 'mit', 'requires-python':    │ │
│ │                       '>=3.9', 'authors': [{'name': 'Joseph Tonic Pollack', 'email': 'joseph.pollack@emle.eu'}], │ │
│ │                       'keywords': ['gradio-custom-component', 'gradio-template-Image', 'seq', 'sequence',        │ │
│ │                       'multiple sequence alignment', 'MSA', 'seqlogo', 'histogram', 'consensus', 'pyplot',       │ │
│ │                       'MSAplot', 'annotation'], 'dependencies': ['gradio>=5.0', 'numpy', 'pillow', 'matplotlib', │ │
│ │                       'pandas', 'seaborn'], 'classifiers': ['Development Status :: 3 - Alpha', 'Operating System │ │
│ │                       :: OS Independent', 'Programming Language :: Python :: 3', 'Programming Language :: Python │ │
│ │                       :: 3 :: Only', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: │ │
│ │                       3.9', 'Programming Language :: Python :: 3.10', 'Programming Language :: Python :: 3.11',  │ │
│ │                       'Topic :: Scientific/Engineering', 'Topic :: Scientific/Engineering :: Artificial          │ │
│ │                       Intelligence', 'Topic :: Scientific/Engineering :: Visualization'], 'repository':          │ │
│ │                       'https://github.com/MedTonic/Gradio-Seq-Diff', 'optional-dependencies': {'dev': ['build',  │ │
│ │                       'twine']}}, 'tool': {'hatch': {'build': {'artifacts':                                      │ │
│ │                       ['/backend/gradio_seq_diff/templates', '*.pyi'], 'targets': {'wheel': {'packages':         │ │
│ │                       ['/backend/gradio_seq_diff']}}}}}}                                                         │ │
│ │         python_path = 'C:\\Users\\MeMyself\\AppData\\Local\\Microsoft\\WindowsApps\\python3.EXE'                 │ │
│ │             version = '0.0.2'                                                                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Could not find `@gradio/preview`. Run `npm i -D @gradio/preview` in your frontend folder.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 5.0.0b3
gradio_client version: 1.4.0b2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.3.0
fastapi: 0.108.0
ffmpy: 0.3.2
gradio-client==1.4.0-beta.2 is not installed.
httpx: 0.27.0
huggingface-hub: 0.24.7
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 1.26.4
orjson: 3.10.1
packaging: 24.0
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.9.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.1
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.24.7
packaging: 24.0
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by hcc226** [comment]
got the same error when I run gradio cc dev

**Comment by Josephrp** [comment]
sorry to hear that , did yours also get published to pypi ? i'm quite sure mine did, the docs autobuild also looks quite nice , i think it's when to push to huggingface (for the demo) and publish to the catalogue. I was just going to try to make a space based on it now , and see , normally it's build / published now 🤷🏻‍♂️🤷🏻‍♂️

**Comment by hcc226** [comment]
您的邮件已收到，我会尽快处理~                                          by 四川大学计算机学院黄聪聪

**Comment by hcc226** [comment]
> sorry to hear that , did yours also get published to pypi ? i'm quite sure mine did, the docs autobuild also looks quite nice , i think it's when to push to huggingface (for the demo) and publish to the catalogue. I was just going to try to make a space based on it now , and see , normally it's build / published now 🤷🏻‍♂️🤷🏻‍♂️

I got this error when I run [gradio cc dev]. I also need to publish it but I am not able to preview the component I created

**Comment by freddyaboulton** [comment]
Apologies. There is a workaround while we fix this that will enable you to run build/dev. Will share when I'm back at a computer.

**Comment by Josephrp** [comment]
wonderful news :-) :-)

**Comment by hcc226** [comment]
I use Gradio 5.0.0b3 and got the same error. May I know what's the gradio/preview version are you using?

**Comment by Josephrp** [comment]
> Apologies. There is a workaround while we fix this that will enable you to run build/dev. Will share when I'm back at a computer.

dont forget us 😉 looking forward to a productive weekend 🚀

**Comment by Col0ring** [comment]
I have met the same error. Just edit `frontend/package.json` and change `@gradio/preview` version to `0.10.1` can resolve this.

**Comment by lth-mettadepth** [comment]
Hi team, 

> I have met the same error. Just edit `frontend/package.json` and change `@gradio/preview` version to `0.10.1` can resolve this.

I getting this when downgrade @gradio/preview version

```
(gradio) lthun@thenHung:/mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent$ gradio cc dev
♻ Launching demo/app.py in reload mode
Watching: 
'/mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/frontend',
'/mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/demo
' '/mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent'
Backend Server:  http://127.0.0.1:7869/
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at join (node:path:1171:7)
    at file:///mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/frontend/node_modules/@gradio/preview/dist/index.js:238:7
    at Array.reduce (<anonymous>)
    at generate_imports (file:///mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/frontend/node_modules/@gradio/preview/dist/index.js:225:37)
    at async create_server (file:///mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/frontend/node_modules/@gradio/preview/dist/index.js:129:29) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v18.20.3
Backend server failed to launch. Exiting.
```

**Comment by abidlabs** [comment]
Hi folks, we just merged in @Col0ring's PR to fix this issue. Can you try installing `gradio` from `main`:

```
pip install https://gradio-builds.s3.amazonaws.com/7894e159197b62122064218f22ad0d78dbac917f/gradio-4.44.0-py3-none-any.whl
```

We will also release Gradio 4.44.1 with this fix.

**Comment by lth-mettadepth** [comment]
Hi Team, I'm installing gradio version 4.4.1 but the issue still not revolved, currently encounter this issue:
```
(gradio_custom) lthun@thenHung:~/win-home/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent$ gradio cc dev
♻ Launching demo/app.py in reload mode

Watching: 
'/mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/frontend',
'/mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/demo
' '/mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent'

Backend Server:  http://127.0.0.1:7860



node:internal/errors:496

    ErrorCaptureStackTrace(err);

    ^



TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object

    at new NodeError (node:internal/errors:405:5)

    at validateString (node:internal/validators:162:11)

    at join (node:path:1171:7)

    at file:///mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/frontend/node_modules/@gradio/preview/dist/index.js:244:7

    at Array.reduce (<anonymous>)

    at generate_imports (file:///mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/frontend/node_modules/@gradio/preview/dist/index.js:231:37)

    at async create_server (file:///mnt/c/Users/lthun/Desktop/workspace/Gradio_lib/gradio_reseach/mycomponent/frontend/node_modules/@gradio/preview/dist/index.js:129:29) {

  code: 'ERR_INVALID_ARG_TYPE'

}

Node.js v18.20.3


Backend server failed to launch. Exiting.
```
Could anyone support me on this issue ?

**Comment by abidlabs** [comment]
Did you install `4.4.1` or `4.44.1`?

**Comment by Col0ring** [comment]
Update the `@gradio/preview` version to `0.11.2` is enough to resolve this issue. Your error seems to be another one, you may need to check the `package.json` of your custom component and verify the field `exports.example` is a string.

**Comment by lth-mettadepth** [comment]
I'm just initialize project follow the Gradio instruction.
```
gradio cc create MyComponent --template SimpleTextbox
cd mycomponent
gradio cc dev
```

the current `package.json`
```json
{
  "name": "gradio_mycomponent",
  "version": "0.2.13",
  "description": "Gradio UI packages",
  "type": "module",
  "author": "",
  "license": "ISC",
  "private": false,
  "main_changeset": true,
  "exports": {
    ".": {
      "gradio": "./Index.svelte",
      "svelte": "./dist/Index.svelte",
      "types": "./dist/Index.svelte.d.ts"
    },
    "./example": {
      "gradio": "./Example.svelte",
      "svelte": "./dist/Example.svelte",
      "types": "./dist/Example.svelte.d.ts"
    },
    "./package.json": "./package.json"
  },
  "dependencies": {
    "@gradio/atoms": "0.8.1",
    "@gradio/icons": "0.7.2",
    "@gradio/statustracker": "0.7.6",
    "@gradio/utils": "0.6.1"
  },
  "devDependencies": {
    "@gradio/preview": "0.11.2"
  },
  "peerDependencies": {
    "svelte": "^4.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gradio-app/gradio.git",
    "directory": "js/simpletextbox"
  }
}
```

Did you find any thing wrong here ?

**Comment by Col0ring** [comment]
> I'm just initialize project follow the Gradio instruction.
> 
> ```
> gradio cc create MyComponent --template SimpleTextbox
> cd mycomponent
> gradio cc dev
> ```
> 
> the current `package.json`
> 
> ```json
> {
>   "name": "gradio_mycomponent",
>   "version": "0.2.13",
>   "description": "Gradio UI packages",
>   "type": "module",
>   "author": "",
>   "license": "ISC",
>   "private": false,
>   "main_changeset": true,
>   "exports": {
>     ".": {
>       "gradio": "./Index.svelte",
>       "svelte": "./dist/Index.svelte",
>       "types": "./dist/Index.svelte.d.ts"
>     },
>     "./example": {
>       "gradio": "./Example.svelte",
>       "svelte": "./dist/Example.svelte",
>       "types": "./dist/Example.svelte.d.ts"
>     },
>     "./package.json": "./package.json"
>   },
>   "dependencies": {
>     "@gradio/atoms": "0.8.1",
>     "@gradio/icons": "0.7.2",
>     "@gradio/statustracker": "0.7.6",
>     "@gradio/utils": "0.6.1"
>   },
>   "devDependencies": {
>     "@gradio/preview": "0.11.2"
>   },
>   "peerDependencies": {
>     "svelte": "^4.0.0"
>   },
>   "repository": {
>     "type": "git",
>     "url": "git+https://github.com/gradio-app/gradio.git",
>     "directory": "js/simpletextbox"
>   }
> }
> ```
> 
> Did you find any thing wrong here ?

Try changing
```json
"exports": {
  ".": {
    "gradio": "./Index.svelte",
    "svelte": "./dist/Index.svelte",
    "types": "./dist/Index.svelte.d.ts"
  },
  "./example": {
    "gradio": "./Example.svelte",
    "svelte": "./dist/Example.svelte",
    "types": "./dist/Example.svelte.d.ts"
  },
  "./package.json": "./package.json"
},
```
to
```json
"exports": {
  ".": "./Index.svelte",
  "./example":  "./Example.svelte",
  "./package.json": "./package.json"
},
```

**Comment by Josephrp** [comment]
will update accordingly - big thanks @Col0ring , with all my thanks ! big congrats to @abidlabs and team for a cool release .
