### ISSUE TITLE
Gradio5 SSR - RuntimeError: Response content longer than Content-Length

### ISSUE THREAD

**Issue by yoonniverse** [gradio-app/gradio#9537]
### Describe the bug

I installed gradio 5 preview to test ssr feature, but encountered "RuntimeError: Response content longer than Content-Length".

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction
```bash
pip install gradio --pre
```

```python
# test.py
import gradio as gr

with gr.Blocks() as demo:
    gr.Dropdown(["apple", "banana"])

demo.launch(ssr_mode=True)
```
```bash
GRADIO_SERVER_NAME=0.0.0.0 python test.py
```

It runs fine when I set `ssr_mode=False`.

### Screenshot

![image](https://github.com/user-attachments/assets/c5aa9976-75fb-43d3-906e-887d3c49031e)

### Logs

```shell
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 736, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/contextlib.py", line 153, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/base.py", line 188, in __call__
    |     await response(scope, wrapped_receive, send)
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/responses.py", line 153, in __call__
    |     await send({"type": prefix + "http.response.body", "body": self.body})
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in _send
    |     await send(message)
    |   File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 528, in send
    |     raise RuntimeError("Response content longer than Content-Length")
    | RuntimeError: Response content longer than Content-Length
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/base.py", line 188, in __call__
    await response(scope, wrapped_receive, send)
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/responses.py", line 153, in __call__
    await send({"type": prefix + "http.response.body", "body": self.body})
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in _send
    await send(message)
  File "/home/ubuntu/miniconda3/envs/gradio5/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 528, in send
    raise RuntimeError("Response content longer than Content-Length")
RuntimeError: Response content longer than Content-Length
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.0.0b5
gradio_client version: 1.4.0b2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.0
fastapi: 0.115.0
ffmpy: 0.4.0
gradio-client==1.4.0-beta.2 is not installed.
httpx: 0.27.2
huggingface-hub: 0.25.1
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 2.1.1
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.3
pillow: 10.4.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart: 0.0.12
pyyaml: 6.0.2
ruff: 0.6.9
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.31.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.2
huggingface-hub: 0.25.1
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @yoonniverse can you try again with the latest beta release we just released? It should be version 5.0.0b6

**Comment by yoonniverse** [comment]
Thanks for the review, but I still have the same issue after upgrading to 5.0.0b6 too.

**Comment by yoonniverse** [comment]
- browser: chrome / edge
- Python: 3.10
- Node: v20.18.0
Yes I'm on linux. I'm testing with aws Lightsail instance.

**Comment by jmetzen** [comment]
I am getting a very the similar error with gradio 5.0.1:

>   ...
>   File "/.venv/lib/python3.11/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
>  File "/.venv/lib/python3.11/site-packages/h11/_writers.py", line 65, in __call__
    self.send_data(event.data, write)
>  File "/.venv/lib/python3.11/site-packages/h11/_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
> h11._util.LocalProtocolError: Too much data for declared Content-Length

Any workarounds?

**Comment by Ethan-yt** [comment]
same here

**Comment by Ethan-yt** [comment]
browser: chrome / safari
Python: 3.12
Node: v22.10.0
gradio: 5.3.0

macos

**Comment by jmetzen** [comment]
I am still getting this error. Any idea how it can be resolved @abidlabs ?

**Comment by abidlabs** [comment]
This should be fixed in the latest version of Gradio (5.19). If not, please provide a repro and I'll reopen this issue!
